<?php
/**
 * The Trident configuration this site needs.
 *
 * @package Qoliber\TridentWoo
 */

declare( strict_types=1 );

namespace Qoliber\TridentWoo\Admin;

use Qoliber\TridentWoo\Cache\WooPolicy;

/**
 * Renders the site-specific part of trident.toml: hosts, the private page
 * paths, and the pass rule for this site's logged-in cookie.
 */
final class ConfigSnippet {

	/**
	 * @return string TOML.
	 */
	public static function toml(): string {
		$home  = (string) wp_parse_url( home_url( '/' ), PHP_URL_HOST );
		$port  = wp_parse_url( home_url( '/' ), PHP_URL_PORT );
		$hosts = array( $home );
		if ( null !== $port && false !== $port ) {
			$hosts[] = $home . ':' . (int) $port;
		}
		if ( ! str_starts_with( $home, 'www.' ) ) {
			$hosts[] = 'www.' . $home;
		}
		// Raw regular expressions; $quote() escapes them for TOML.
		$paths = array( '^/wp-admin(/|$)', '^/wp-login\.php', '^/wp-cron\.php', '^/xmlrpc\.php', '^/wp-json(/|$)' );
		if ( function_exists( 'wc_get_page_id' ) ) {
			foreach ( array( 'cart', 'checkout', 'myaccount' ) as $page ) {
				$id = wc_get_page_id( $page );
				if ( $id > 0 ) {
					$path = rtrim( (string) wp_parse_url( (string) get_permalink( $id ), PHP_URL_PATH ), '/' );
					if ( '' !== $path ) {
						$paths[] = '^' . preg_quote( $path, '' ) . '(/|$)';
					}
				}
			}
		}
		$quote = static fn ( string $s ): string => '"' . str_replace( array( '\\', '"' ), array( '\\\\', '\\"' ), $s ) . '"';
		$lines = array(
			'# Generated by `wp trident config` for ' . home_url( '/' ),
			'# Merge into trident.toml; see the plugin README for the full file and the why.',
			'',
			'[server]',
			'preserve_host = true',
			'',
			'[cache.key]',
			'cache_with_cookies = true',
			'bypass_query_params = [' . implode( ', ', array_map( $quote, WooPolicy::BYPASS_QUERY ) ) . ']',
			'pass_patterns = [' . implode( ', ', array_map( $quote, array_values( array_unique( $paths ) ) ) ) . ']',
			'',
			'[cache.tags]',
			'headers = ["X-Cache-Tags"]',
			'separator = ","',
			'strip_header = true',
			'',
			'[cache.poisoning]',
			'enabled = true',
			'known_hosts = [' . implode( ', ', array_map( $quote, $hosts ) ) . ']',
			'',
			'# Shared blocks as fragments, per-request tokens as private fragments.',
			'[esi]',
			'enabled = true',
			'mode = "hole_punch"',
			'content_types = ["text/html"]',
			'propagate_headers = ["Host"]',
			'allowed_hosts = [' . implode( ', ', array_map( $quote, $hosts ) ) . ']',
			'',
			'# HTML is stored only when the plugin said `public`.',
			'[[rules.response]]',
			'name = "html_needs_explicit_public"',
			'match = { header = { "Content-Type" = { pattern = "^text/html", ignore_case = true } }, not_header = { "Cache-Control" = { pattern = "public", ignore_case = true } } }',
			'action = "pass"',
			'priority = 150',
			'',
			'# This site\'s logged-in cookie is ' . ( defined( 'LOGGED_IN_COOKIE' ) ? LOGGED_IN_COOKIE : 'wordpress_logged_in_<hash>' ) . ';',
			'# the pattern covers it and the other per-user cookies.',
			'[[rules.request]]',
			'name = "wordpress_logged_in"',
			'match = { header = { "Cookie" = { pattern = ' . $quote( '(^|;\s*)(' . implode( '|', array_map( static fn ( string $p ): string => preg_quote( $p, '' ), WooPolicy::LOGGED_IN_COOKIES ) ) . ')' ) . ' } } }',
			'action = "pass"',
			'priority = 100',
			'',
			'[[rules.request]]',
			'name = "post_requests"',
			'match = { method = "POST" }',
			'action = "pass"',
			'priority = 70',
		);
		return implode( "\n", $lines );
	}
}
